matrix:
  include:
    - language: elixir
      elixir:
        - '1.10.2'
      otp_release:
        - '22.2.8'
    - language: general
      sudo: required
      services:
        - docker
      install:
        - docker build .
notifications:
  email:
    on_success: never 
    on_failure: change
