version: '3'

services:
  back-account:
    build: .
    ports:
        - "4000:4000"
    command: start
    depends_on:
      - db
  db:
    image: postgres
    environment:
       POSTGRES_DB: 'test'
       POSTGRES_USER: 'test'
       POSTGRES_PASSWORD: 'test'
    ports:
      - "5432:5432"

